# Generated by Django 3.0.2 on 2020-02-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='distrito',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(choices=[('V', 'Varon'), ('M', 'Mujer')], max_length=20, null=True),
        ),
    ]
