# Generated by Django 3.0.2 on 2020-02-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0002_auto_20200219_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('raza', models.CharField(max_length=50)),
                ('años', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=20, null=True)),
                ('alergia', models.CharField(max_length=200)),
            ],
        ),
    ]
