# Generated by Django 3.0.2 on 2020-02-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0003_mascota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='años',
        ),
        migrations.AddField(
            model_name='mascota',
            name='edad',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='alergia',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
