# Generated by Django 3.0.2 on 2020-02-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0004_auto_20200219_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.IntegerField(null=True),
        ),
    ]
