# Generated by Django 3.0.2 on 2020-02-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0005_auto_20200219_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paseador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('sexo', models.CharField(choices=[('V', 'Varon'), ('M', 'Mujer')], max_length=20, null=True)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=15)),
                ('experiencia', models.CharField(max_length=15)),
                ('distrito', models.CharField(max_length=200)),
            ],
        ),
    ]
